backend_repo_url: "https://github.com/pravinmishraaws/book-review-app.git"
backend_app_port: 3001
db_host: "dmi-bookreview-db.mysql.database.azure.com"
db_user: "mysqladmin"
db_password: "DevSecureDBPassword123!"
db_name: "bookreviews_dev"
jwt_secret: "your_jwt_secret"
allowed_origins: "http://52.230.94.84:3000"
